# Generated by Django 5.0.3 on 2024-04-04 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_otpgenerationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otpGenerationTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 4, 17, 27, 9, 254260, tzinfo=datetime.timezone.utc)),
        ),
    ]
