# Generated by Django 5.0.3 on 2024-04-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_otpgenerationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otpGenerationTime',
            field=models.DateTimeField(blank=True),
        ),
    ]
